### ISSUE TITLE
email sending error

### ISSUE THREAD

**Issue by ttibensky** [symfony/SwiftmailerBundle#93]
I'm trying to send email to this example address: `tomáš.example@gmail.com` which is ok under RFC6531 standard and it passes through form validation using this code:

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add(
                'email',
                'text',
                array(
                    'constraints' => array(
                        new NotBlank(),
                        new Email(
                            array(
                                'strict' => true,
                                'checkMX' => true,
                                'checkHost' => true
                            )
                        ),
                    ),
                )
            )

however, I'm getting this error:

    [Swift_RfcComplianceException]
    Address in mailbox given [tomáš.example@gmail.com] does not comply with RFC 2822, 3.6.2.

is it a problem in swiftmailer bundle or SMTP server? if it is in the bundle, how can I change the RFC standard to make this work? thank you for help

**Comment by sstok** [comment]
https://github.com/swiftmailer/swiftmailer/search?utf8=%E2%9C%93&q=RFC+2822&type=Issues
https://github.com/swiftmailer/swiftmailer/issues/403

This is a known limitation, the last link prepossess a solution.
